services:
  - type: web
    name: subscription-api
    env: python
    buildCommand: cd backend/subscription-api && pip install -r requirements.txt
    startCommand: cd backend/subscription-api && gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        value: rzp_test_demo
      - key: RAZORPAY_KEY_SECRET
        value: demo_secret
  
  - type: static
    name: user-portal
    buildCommand: cd frontend/user-portal && npm install && npm run build
    staticPublishPath: frontend/user-portal/dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://subscription-api.onrender.com/*
      - type: rewrite
        source: /*
        destination: /index.html